### ISSUE TITLE
Terraform crashes

### ISSUE THREAD

**Issue by baurmatt** [mumoshu/terraform-provider-helmfile#37]
## Versions

Terraform v0.12.28
+ provider.helmfile v0.7.4

## helmfile.yaml
```yaml
repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

helmDefaults:
  wait: true

releases:
  - name: heapster
    namespace: kube-system
    chart: stable/heapster
    version: 0.3.2
    values:
    - "./config/heapster/values.yaml"
    - "./config/heapster/{{ .Environment.Name }}.yaml"
    secrets:
    - "./config/heapster/secrets.yaml"
    - "./config/heapster/{{ .Environment.Name }}-secrets.yaml"
```

## main.tf
```terraform
provider "helmfile" {}
resource "helmfile_release_set" "mystack" {
  content = file("./helmfile.yaml")

  environment_variables = {
    KUBECONFIG = "${path.cwd}/kubeconfig-admin-PersonalClusters-mysql-test"
  }
}
```

(I can't share the kubeconfig file but I can ensure you that it is valid)

## crash.log
[crash.log](https://github.com/mumoshu/terraform-provider-helmfile/files/5259933/crash.log)
